# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Ethan O'Hanlon - Game Programmer
# Description of the Site
description: Game Programmer & Enthusiast
# URL of Image of the Site
site-image: /assets/images/logo.png
# Keywords of the Site
site-keywords: Games, Programming, Development
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://www.youtube.com/watch?v=l554kV12Wuo&ab_channel=InsiderNews

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ethan.ohanlon243@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
itch_username: eohanlon243
linkedin_username: ethan-o-hanlon-44b94518a
github_username:  EOHanlon243
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: eohanlon243

# Name of the Author
author-name: Ethan O'Hanlon
# URL for the Image of the Author
author-image: /assets/images/author.jpg
# 60 Words About the Author
author-about: Howdy! I'm Ethan. I'm a Level 5 University of Portsmouth student, studying Computer Games Technology. My passion is learning about / creating games, as a medium of entertainment and as an experience. My joy comes from programming games, everything from gameplay features, streamline features and the arithmetic behind it all; other aspects of game development intrigue me as well. I have a keen interest in music composition / playing keyboard, I like to watch anime and read manga and I love playing story-driven single player games (especially JRPG's and Action games).
author-about-short: I'm a Level 5 University of Portsmouth student, studying Computer Games Technology.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/EOHanlon243

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
